name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: avinashkale/wisecow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Create .kube directory
      run: mkdir -p $HOME/.kube

    - name: Check .kube directory permissions
      run: |
        echo "Checking .kube directory permissions..."
        ls -ld $HOME/.kube
        if [ -d "$HOME/.kube" ]; then
          echo ".kube directory exists with appropriate permissions."
        else
          echo ".kube directory does not exist or has incorrect permissions."
          exit 1
        fi

    - name: Configure Kubeconfig
      run: |
        echo "Configuring kubeconfig..."
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
      continue-on-error: true

    - name: Verify kubeconfig file
      run: |
        echo "Verifying kubeconfig file..."
        if [ -f $HOME/.kube/config ]; then
          echo "Kubeconfig successfully created"
          ls -l $HOME/.kube/config
        else
          echo "Kubeconfig creation failed"
          exit 1
        fi

    - name: Deploy to Kubernetes
      run: |
        echo "Deploying to Kubernetes..."
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f ingress.yaml

